FROM python:3.12-slim

WORKDIR /app

ENV UV_PROJECT_ENVIRONMENT=/opt/venv
ENV PATH="/opt/venv/bin:$PATH"
ENV PYTHONPATH=/app

RUN pip install --no-cache-dir uv==0.9.13

COPY pyproject.toml uv.lock ./
RUN uv sync --frozen --no-dev

COPY app ./app
COPY worker ./worker

CMD ["celery", "-A", "worker.celery_app", "worker", "--loglevel=INFO"]
